### ISSUE TITLE
Route /api/oauth/userinfo couldn't be rendered statically because it accessed `request.headers`

### ISSUE THREAD

**Issue by dor123official** [dubinc/dub#1190] opened 2024-08-15 13:37 UTC
```
web:build: API error occurred Dynamic server usage: Route /api/oauth/userinfo couldn't be rendered statically because it accessed `request.headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
web:build:    Generating static pages (60/80) 
```
how i can fix it?

**Comment by steven-tey** [comment] 2024-08-22 04:50
looks like a duplicate of #1181

**Closed by steven-tey** 2024-08-22 04:50 UTC
