### ISSUE TITLE
What should the output directory be?

### ISSUE THREAD

**Issue by jaiveertalwar** [dubinc/dub#550] opened 2024-01-11 16:33 UTC
I get an error for output directory

**Comment by md-abdul-halim-rafi** [comment] 2024-01-12 03:28
It should be the `.next` and make sure you've set the root directory as `apps/web` from your vercel settings

**Comment by jaiveertalwar** [comment] 2024-01-12 05:49
```
<html>
<body>
<!--StartFragment-->


Error: The Edge Function "middleware" is referencing unsupported modules:
11:18:02.818 | - apps/web/lib/middleware/admin.js: @/lib/middleware/utils
11:18:02.818 | - apps/web/middleware.js: @/lib/middleware, @/lib/middleware/utils
11:18:05.811

<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```
What to do?

**Comment by steven-tey** [comment] 2024-01-15 19:43
Closing as a duplicate of #549

**Closed by steven-tey** 2024-01-15 19:43 UTC
