### ISSUE TITLE
Self Hosting

### ISSUE THREAD

**Issue by h4MeMengoding** [dubinc/dub#1029] opened 2024-06-30 22:48 UTC
hello, it's been more than 2 weeks since I submitted an issue that self hosting dub.co can't be done on vercel free, and the developer needs to fix it, but sadly there's no answer from the developer, but to another question the developer answered, does dub.co still work for self hosting? I hope so!

**Comment by jaiveertalwar** [comment] 2024-07-03 05:18
I have encountered the same issue. I have been trying for upward of 5 weeks but no responses.

**Comment by MFYDev** [comment] 2024-07-03 07:10
I think until this point it is pretty clear that self hosting is not dub's first priority. Seems like the whole repo and the website is pushing users to use their official website. I already switched to Sink, which is also a great url shortner

**Comment by steven-tey** [comment] 2024-07-03 16:11
Closing as a duplicate of #993 – let's focus the discussion there please 🙏

**Closed by steven-tey** 2024-07-03 16:11 UTC
