### ISSUE TITLE
Dockerise Dub

### ISSUE THREAD

**Issue by Pratham271** [dubinc/dub#786] opened 2024-04-16 10:20 UTC
The app itself is not dockerised. I found one docker-compose file that according to me was for mysql and using planet-scale db.I think it would be better to dockerise the complete app for local setup

**Comment by Pratham271** [comment] 2024-04-16 10:21
If its a valid issue. I am willing to make my contribution to the dub.sh @steven-tey ?

**Comment by steven-tey** [comment] 2024-04-18 15:26
Closing as a duplicate of #25

**Closed by steven-tey** 2024-04-18 15:26 UTC
