### ISSUE TITLE
Cannot delete a link with an asterisk in the path

### ISSUE THREAD

**Issue by mashtg** [dubinc/dub#1417] opened 2024-10-12 08:41 UTC
Stupidly I created a link with the structure "[customdomain]/*" and now cannot delete it.

After typing "[customdomain]/* into the delete verification box, the error message is "Please match the format requested."

**Comment by steven-tey** [comment] 2024-10-12 22:39
Thanks for reporting! This is a duplicate of #1324, will get this fixed soon!

**Closed by steven-tey** 2024-10-12 22:39 UTC
