### ISSUE TITLE
Project didn't Start

### ISSUE THREAD

**Issue by zohaibafzal49** [dubinc/dub#812] opened 2024-04-24 09:29 UTC
<img width="953" alt="image" src="https://github.com/dubinc/dub/assets/49705525/258fa05b-f4f6-4f8e-9b94-8b05f3b09bd6">
Error is: "Couldn't find any `pages` or `app` directory. Please create one under the project root".

**Comment by steven-tey** [comment] 2024-04-24 11:16
Duplicate of #599

**Closed by steven-tey** 2024-04-24 11:16 UTC
